version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    networks:
      - personal-dashboard

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: personal-dashboard
    volumes:
      - mongodb_data:/data/db
    networks:
      - personal-dashboard

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - personal-dashboard

volumes:
  neo4j_data:
  neo4j_plugins:
  mongodb_data:
  redis_data:

networks:
  personal-dashboard:
    driver: bridge
